### ISSUE TITLE
Reconfigure sqlite en database.yml

### ISSUE THREAD

**Issue by diegoesp** [diegoesp/pretty_reports#52]
Volvi a poner sqlite en database.yml porque no tengo instalado postgresql. Si queres usar postgresql para desarrollo (entiendo que lo haras para igualar el entorno con heroku o por simple comodidad porque es lo que usas con SCV) avisame asi me lo configuro yo tambien.

**Comment by rafaelchiti** [comment]
Ah si, en realidad en un momento pense en poner el pdf en la base, tonce ya
estaba obligado a usar un motor posta. Pero al final estoy poniendo los pdf
en las carpetas, por ende podemos usar sqlite. Perooooo, lo que me termino
pasando con ese approach es que pierdo tiempo aprendiendo comandos para un
motor que no necesito, por ej, ya se usar bien postgresql, que es lo que
voy a terminar usando, tonce cuando quiero ver la base por consola con
sqlite pierdo tiempo por que no conozco algunos comandos. No hay apuro
alguno, pero si podes intalarte postgresql en algun momento mejor, asi ya
migramos.

2012/8/25 diegoesp notifications@github.com

**Comment by diegoesp** [comment]
OK. Me configuro un postgreSQL apenas pueda y ahi cambio el yml de development

**Comment by rafaelchiti** [comment]
dales, no hay prisa.
