### ISSUE TITLE
Credenciales y acceso a Heroku

### ISSUE THREAD

**Issue by diegoesp** [diegoesp/pretty_reports#53]
Please publicas en la wiki las credenciales y acceso a Heroku ?

Saludos

**Comment by diegoesp** [comment]
Hola ! hay alguien ahi ? McFly ?

**Comment by rafaelchiti** [comment]
no usemos heroku, vamos a usar una caja custom en amaozon u otro lugar, va a ser distinto a heroku, no perdamos con tiempo ahi. Por ej, wkhtmltopdf va a ser un dolor de cabeza configurarlo en heroku. 
Despues instalo un ubuntu en mi caja de amazon y deployo ahi como server de dev y uat. Y usamos tu caja como server productivo.
