### ISSUE TITLE
Error al arrancar webrick o unicorn

### ISSUE THREAD

**Issue by diegoesp** [diegoesp/pretty_reports#60]
Che Rafa, siempre que arranco webrick me tira este error:

/home/despada/Rails/pretty_reports/vendor/bundle/ruby/1.9.1/gems/actionpack-3.2.6/lib/action_dispatch/http/mime_type.rb:102: warning: already initialized constant PDF

Sabes de que es ?

**Comment by rafaelchiti** [comment]
nop, ahora me fijo.

**Comment by diegoesp** [comment]
Ya lo encontre. En mime_types.rb estas registrando por segunda vez el mime
pdf. Lo saque y ahora no lo hace mas. Cuando pushee se integra.
