### ISSUE TITLE
Configurar pdfkit para que devuelva un pdf cuando pedis el reporte con formato .pdf

### ISSUE THREAD

**Issue by rafaelchiti** [diegoesp/pretty_reports#68]
Bueno, te cuento un poco, di bastantes vueltas e inverti unas cuantas horas, no pude hacer andarlo. al menos no sin hacer cabeceadas.

Fijate que hay un branch mio subido a github que se llama pdfkit_pruebas_set1 hace un diff de ese branch con master y vas a ver que fue lo que hice para probar.

Lo que sucede es lo siguiente:
- Si configuras como dice la wiki de pdfkit para que use el middleware y haces que el action show responda a .pdf (fijate en mi branch es una pavada hacer eso). Vas a la url reports/1.pdf y se cuelga, no te responde. Basicamente pasa eso por que no arma bien la url, si te fijas en consola y haces un $ ps aux | grep wkhtml $ vas a ver que esta el comando que tiro la libreria pero al final dice - -  en lugar de decir la url de donde tiene que bajarlo.

Ahora bien para solucionar este problema estan las manganetas que vas a ver en mi branch, en el initializer. Fijate si entendes lo que hacen, basicamente es un problema de donde esta yendo a buscar las cosas.
- Otro problema con el que me tope luego de hacer esas cabeceadas y que funcione es que la libreria no se queda a esperar por las imagenes entonces genera el pdf pero las imagenes no estan, por ahi esto es mas trivial de arreglar, no lelgue a googlear mucho.

Te paso un post de stackoverflow para que veas http://stackoverflow.com/questions/8017042/pdfkit-not-rendering-correctly-in-rails-3-1

De todos modos no lo pude solucionar con ese post.
- Otro detalle, al hacer aputnar la libreria a /public para buscar los assets vas a tener que hacer que esten precompilados los assets sino no los va a encontrar en public. Ejecuta $ bundle exec rake assets:precompile

Avisame si con esto ya estas mas o menos en tema sino lo vemos.  Si no funciona lo del middleware de pdfkit podemos ver de usar wicked_pdf o dar alguna otra vuelta

**Comment by diegoesp** [comment]
Me acabo de dar cuenta que nunca leiste lo que puse en la wiki :P
