### ISSUE TITLE
Filtrar recursos por usuario

### ISSUE THREAD

**Issue by rafaelchiti** [diegoesp/pretty_reports#70]
@diegoesp che esto es copado para que hagas! en todos lados hay que generar filtros por usuario. En los controllers por ej a la hora de devolver un reporte o una lista de reporte hay que preguntar si corresponde el usuario, fijate que hay formas ya establecidas para hacerlo con rails. Asi ya cada usuario ve su reporte nomas!.

**Comment by diegoesp** [comment]
se hace con scopes. Lo hago pero mira que no me va a llevar mucho.
Aprovecha la oferta de pasarme algo de GUI hoy que estoy bueno :P

**Comment by diegoesp** [comment]
Hecho usando un scope llamado my_reports. Ya lo integre al controller.
