### ISSUE TITLE
Pagina de preferencias de usuario

### ISSUE THREAD

**Issue by rafaelchiti** [diegoesp/pretty_reports#71]
@diegoesp jaja bueno aca tenes mas pa hacer. La pagina de editar las preferencias del usuario. Por ahora solo que pueda editar el password, despues vemos que onda. Si estas al re pedo hacete un form para subir imagenes como para que pueda subir el logo de la empresa y de ultima vemos con octavio como lo pnoemos en el reporte (igual hasta mas adelante no creo que lo usemos).

Los estilos tiralos en un archivo nuevo que sea assets/users/edit.css.scss

**Comment by diegoesp** [comment]
ACK !

2012/9/12 Rafael notifications@github.com

**Comment by diegoesp** [comment]
Esta cerrado. No le hice upload de imagenes porque no le veo mucho sentido sin definirlo bien. Pensemos lo del logo y donde lo ponemos, y lo hago.
