### ISSUE TITLE
Pensar un nombre para el producto y registrarlo

### ISSUE THREAD

**Issue by rafaelchiti** [diegoesp/pretty_reports#9]

**Comment by diegoesp** [comment]
agilestatus.com !

**Comment by rafaelchiti** [comment]
Mañana lo repasamos con octavio y tomamos una decision.

**Comment by diegoesp** [comment]
Hay que elegir uno y chequearlo en bustaname antes. Quedamos en que vamos a vincularnos a la palabra "status" sin usar "report" (para no hacerlo muy duro) ni tampoco usar "agile" (para no hacerlo muy blando).

Piensen y tiren opciones aca ! @rafaelchiti @octanko

**Comment by diegoesp** [comment]
swiftstatus.com esta disponible

**Comment by diegoesp** [comment]
Si queremos tener una mascota a la octocat, podriamos vincular a status con un animal. Un juego interesante de palabras es statusoctopus.com (disponible). Es consonante.

**Comment by diegoesp** [comment]
getyourstatus.com tambien esta disponible. Es un toque grasa, la verdad. Pero por ahi sirve como semilla para otra idea.

**Comment by diegoesp** [comment]
Te lo pase a vos a ver si se te cae una idea viejo
